

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
server:
  port: 9527

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2/demo-fs
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: owner
    password: